config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'

  resources :home, only: [:index]
  resources :performances, only: [:index]
  resources :bookings, only: [:index, :new, :create]
  resources :galleries, only: [:index]
  resources :abouts, only: [:index]
  resources :contacts, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :client
  belongs_to :venue
  belongs_to :booking_type, optional: true
  belongs_to :booking_status
  has_many :payments

  accepts_nested_attributes_for :client, :venue

  before_validation do
    self.booking_status ||= BookingStatus.find_by!(status: 'New')
  end
end

app/models/booking_status.rb
class BookingStatus < ApplicationRecord
  has_many :bookings
end

app/models/booking_type.rb
class BookingType < ApplicationRecord
  has_many :bookings
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :bookings

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :phone, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :booking

  validates :booking_id, presence: true
  validates :amount, presence: true
  validates :date, presence: true
  validates :payment_type_id, presence: true
  validates :transaction_status, presence: true
end

app/models/payment_type.rb
class PaymentType < ApplicationRecord
end

app/models/venue.rb
class Venue < ApplicationRecord
  has_many :bookings

  validates :name, presence: true
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    redirect_to new_booking_path
  end

  def new
    @booking = Booking.new
    @booking.build_client
    @booking.build_venue
  end

  def create
    @booking = Booking.new(b_params)

    if @booking.save
      flash[:notice] = "Booking request successfully submitted"
      redirect_to bookings_path
    else
      render :new
    end
  end

  private

  def b_params
    params.require(:booking).permit(
      :date,
      :time,
      :duration,
      :budget,
      :booking_type_id,
      :booking_status_id,
      client_attributes: [
        :first_name,
        :last_name,
        :company,
        :address,
        :city,
        :state,
        :zip,
        :country,
        :email,
        :phone ],
      venue_attributes: [
        :name,
        :address,
        :city,
        :state,
        :zip,
        :country
      ]
    )
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    redirect_to new_contact_path
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(i_params)

    if @contact.save
      name = params[:name]
      email = params[:email]
      comment = params[:comment]

      ApplicationMailer.welcome_email(@contact).deliver_now

      flash[:notice] = "Inquiry successfully submitted"
      redirect_to contacts_path
    else
      render :new
    end
  end

  private

  def i_params
    params.require(:contact).permit(
      :name,
      :email,
      :comment
    )
  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  render 'layouts/home'
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/performances_helper.rb
module PerformancesHelper
end

app/views/layouts/_head.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Vertical Tango | Sandra Feusi &amp; Samuel Pyne</title>
    <%= csrf_meta_tags %>

    <meta name=“ROBOTS” content=“NOINDEX, NOFOLLOW”>

    <!-- bootstrap required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <link href='https://fonts.googleapis.com/css?family=Monsieur+La+Doulaise' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Limelight' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Oswald' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif' rel='stylesheet'>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- bootstrap required js -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
  </head>

app/views/layouts/application.html.erb
<%= render 'layouts/head' %>

  <body>
    <div class="container-fluid" id="main-img" style="background-image: url('<%= asset_path("#{controller_name}.jpg") %>');">
      <div id="nav" class="row v-align">
        <div class="col-6">
          <%= link_to "Vertical Tango", root_path, class: "logo" %>
          &nbsp; <span class="performer"> SANDRA FEUSI &amp; SAMUEL PYNE</span>
        </div>
        <div class="col">
          <ul class="nav justify-content-end">
            <li class="nav-item"><%= link_to "PERFORMANCES", performances_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "BOOK A SHOW", bookings_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "GALLERY", galleries_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "ABOUT", abouts_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "CONTACT US", contacts_path, class: "nav-link" %></li>
          </ul>
        </div>
      </div>
      <div style="color: #808080; font-size: 50px; text-align: center; margin-top: 150px;">
        PLACEHOLDER IMAGE
      </div>
    </div>

    <div class="main">
      <%# flash.each do |key, value| %>
        <!-- <strong><%#= content_tag :div, value, class: "flash #{key}" %></strong> -->
      <%# end %>
      <%= yield %>
    </div>

    <div class="footer">
      Copyright: Sandra Feusi &amp; Samuel Pyne
    </div>

  </body>
</html>

app/views/layouts/home.html.erb
<%= render 'layouts/head' %>
  <body class="home">
    <div class="container-fluid home">
      <div id="nav" class="row v-align">
        <div class="col-6">
          <%#= link_to "Vertical Tango", root_path, id: "logo" %>
          <!-- &nbsp; <span id ="performer"> SANDRA FEUSI &amp; SAMUEL PYNE</span> -->
        </div>
        <div class="col">
          <ul class="nav justify-content-end">
            <li class="nav-item"><%= link_to "PERFORMANCES", performances_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "BOOK A SHOW", bookings_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "GALLERY", galleries_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "ABOUT", abouts_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "CONTACT US", contacts_path, class: "nav-link" %></li>
          </ul>
        </div>
      </div>
      <div class="row middle-align">
        <div class="col-4"></div>
        <div class="col-4 home-text">
          <p><span class="logo logo-home">Vertical<br />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tango</span></p>
          <p class="performer performer-home">SANDRA FEUSI &amp; SAMUEL PYNE</p>
        </div>
        <div class="col-4"></div>
      </div>
    </div>

    <div class="footer footer-home">
      Copyright: Sandra Feusi &amp; Samuel Pyne
    </div>

  </body>
</html>